# Generated by Django 2.1 on 2020-08-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='memo',
            field=models.TextField(blank=True, verbose_name='MEMO'),
        ),
    ]
